name: autoupdate

on:
  workflow_dispatch:
  schedule:
    - cron: '42 9 * * *'

permissions:
  pull-requests: write
  contents: write

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: source
      - name: Install prerequisites
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends iucode-tool sqlite3 unzip
      - name: Update microcode versions
        run: ./scripts/update_mcedb.sh
      - name: Update Intel models
        run: ./scripts/update_intel_models.sh
      - name: Check git diff
        id: diff
        run: |
          echo change="$(git diff | awk '/MCEDB/ { if(V) { print V" to "$4; exit } else { V=$4 } }')" >> "$GITHUB_OUTPUT"
          echo nbdiff="$(git diff | grep -cE -- '^\+# [AI],')" >> "$GITHUB_OUTPUT"
          git diff
          cat "$GITHUB_OUTPUT"
      - name: Create Pull Request if needed
        if: steps.diff.outputs.nbdiff != '0'
        uses: peter-evans/create-pull-request@v7
        with:
          branch: autoupdate-fwdb
          commit-message: "update: fwdb from ${{ steps.diff.outputs.change }}, ${{ steps.diff.outputs.nbdiff }} microcode changes"
          title: "[Auto] Update fwdb from ${{ steps.diff.outputs.change }}"
          body: |
            Automated PR to update fwdb from ${{ steps.diff.outputs.change }}
            Detected ${{ steps.diff.outputs.nbdiff }} microcode changes
